# Generated by Django 5.1.6 on 2025-11-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_description_alter_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(auto_now=True, help_text='The date when the task is due.'),
        ),
    ]
